Attribute VB_Name = "modData"
Global i As Integer, j As Integer, k As Integer, PresentDay As Long
Global Umax As Integer, BSmax As Integer, GMmax As Integer, Itt As Integer
Global LineWidth As Long
Global Nameof As String
Global Holder(40) As String
Global Dateof(365) As String
Global BreakfastTime(365) As String
Global LunchTime(365) As String
Global DinnerTime(365) As String
Global BSnackTime(365) As String
Global LSnackTime(365) As String
Global DSnackTime(365) As String
Global BreakfastMealText(365) As String
Global LunchMealText(365) As String
Global DinnerMealText(365) As String
Global BSnackMealText(365) As String
Global LSnackMealText(365) As String
Global DSnackMealText(365) As String
Global BSBr(365) As String
Global BSLu(365) As String
Global BSDin(365) As String
Global BSBs(365) As String
Global BSLs(365) As String
Global BSDs(365) As String
Global UnitsBr(365) As String
Global UnitsLu(365) As String
Global UnitsDin(365) As String
Global UnitsBs(365) As String
Global UnitsLs(365) As String
Global UnitsDs(365) As String
Global CHOBr(365) As String
Global CHOLu(365) As String
Global CHODin(365) As String
Global CHOBs(365) As String
Global CHOLs(365) As String
Global CHODs(365) As String
Global TimeBr(365) As String
Global TimeLu(365) As String
Global TimeDin(365) As String
Global TimeBs(365) As String
Global TimeLs(365) As String
Global TimeDs(365) As String
